// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying connectivity to the StoryMaker AI MCP server.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-story-templates.ts
import { createClient } from "npm:@supabase/supabase-js@^2.74.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_story_templates_default = defineTool2({
  name: "list_story_templates",
  title: "List story templates",
  description: "List publicly available StoryMaker AI story templates. Optionally filter by age group or genre to narrow results.",
  inputSchema: {
    ageGroup: z2.string().optional().describe("Optional age group filter, e.g. 'kids', 'teens', 'adults'."),
    genre: z2.string().optional().describe("Optional genre filter, e.g. 'fantasy', 'mystery'."),
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum number of templates to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ ageGroup, genre, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("story_templates").select("id, name, genre, description, starter_text, age_group").limit(limit ?? 20);
    if (ageGroup) query = query.eq("age_group", ageGroup);
    if (genre) query = query.eq("genre", genre);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { templates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/generate-story-idea.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var generate_story_idea_default = defineTool3({
  name: "generate_story_idea",
  title: "Generate story idea",
  description: "Generate a short, original story idea (title + 3-sentence premise) using StoryMaker AI. Provide a theme, age group, and optional genre.",
  inputSchema: {
    theme: z3.string().min(1).describe("Theme or concept to base the story on."),
    ageGroup: z3.string().optional().describe("Target age group (e.g. 'kids', 'teens', 'adults'). Defaults to 'adults'."),
    genre: z3.string().optional().describe("Optional genre, e.g. 'fantasy'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ theme, ageGroup, genre }) => {
    const apiKey = process.env.LOVABLE_API_KEY;
    if (!apiKey) {
      return {
        content: [{ type: "text", text: "LOVABLE_API_KEY is not configured." }],
        isError: true
      };
    }
    const prompt = `Generate an original story idea for ${ageGroup ?? "adults"}${genre ? ` in the ${genre} genre` : ""} based on the theme: "${theme}". Return a compelling title on the first line, then a 3-sentence premise.`;
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Lovable-API-Key": apiKey
      },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: "You are a creative story-idea generator for StoryMaker AI." },
          { role: "user", content: prompt }
        ]
      })
    });
    if (!res.ok) {
      const errText = await res.text();
      return {
        content: [{ type: "text", text: `AI Gateway error (${res.status}): ${errText}` }],
        isError: true
      };
    }
    const json = await res.json();
    const text = json?.choices?.[0]?.message?.content ?? "";
    return {
      content: [{ type: "text", text }],
      structuredContent: { idea: text, theme, ageGroup: ageGroup ?? "adults", genre: genre ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "storymaker-ai-mcp",
  title: "StoryMaker AI",
  version: "0.1.0",
  instructions: "Tools for StoryMaker AI. Use `echo` to verify connectivity, `list_story_templates` to browse available public story templates by age group or genre, and `generate_story_idea` to generate an original story premise from a theme.",
  tools: [echo_default, list_story_templates_default, generate_story_idea_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
